const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://th.bing.com/th/id/OIP.TVYl8zaIREuqTW0FF04hOQHaJX?w=180&h=228&c=7&r=0&o=5&pid=1.7',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://www.fastfoodmenunutrition.com/wp-content/uploads/2015/03/fast-food.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://www.opposingviews.com/.image/t_share/MTU0MDAwOTg4NjcxMDU5NzA3/teen-arrested-for-smearing-menstrual-blood-on-fast-food-photo-promo-image.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://i2.wp.com/www.tastyislandhawaii.com/images11/burgers_on_the_edge/burgers_edge_plate65.jpg?resize=500%2C295',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://th.bing.com/th/id/OIP.lOTEaIPouTHGZ6hO7EgP7QHaHa?w=180&h=180&c=7&r=0&o=5&pid=1.7',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://th.bing.com/th/id/OIP.j1zAMngJMqplOMl7XtJ-WAHaLH?w=180&h=270&c=7&r=0&o=5&pid=1.7',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://th.bing.com/th/id/OIP.VIiN8rilxb2kvX0zjxPOxAHaKH?w=180&h=247&c=7&r=0&o=5&pid=1.7',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://th.bing.com/th/id/OIP.8LrZ_qUwNboJHd9qb1pkQAHaLH?w=180&h=270&c=7&r=0&o=5&pid=1.7',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://th.bing.com/th/id/OIP.Mh8swsoI-PDSHdue8Iqv6wHaKJ?w=180&h=247&c=7&r=0&o=5&pid=1.7',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 17.99,
    img: 'https://th.bing.com/th/id/OIP.pMS1ZOhJJygz6a1eg1S1JwHaLH?w=180&h=270&c=7&r=0&o=5&pid=1.7',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;